"""Add fleet summary analytics columns

Revision ID: 22a74425feb4
Revises: 010
Create Date: 2026-07-12 10:31:58.923699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22a74425feb4'
down_revision: Union[str, None] = '010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_checkpoints', sa.Column('processor_group', sa.String(length=50), nullable=False))
    op.add_column('analytics_checkpoints', sa.Column('last_processed_id', sa.Integer(), nullable=False))
    op.add_column('analytics_checkpoints', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('analytics_checkpoints_pipeline_name_key'), 'analytics_checkpoints', type_='unique')
    op.drop_index(op.f('ix_analytics_checkpoints_id'), table_name='analytics_checkpoints')
    op.create_index(op.f('ix_analytics_checkpoints_processor_group'), 'analytics_checkpoints', ['processor_group'], unique=False)
    op.drop_column('analytics_checkpoints', 'last_run_timestamp')
    op.drop_column('analytics_checkpoints', 'pipeline_name')
    op.drop_column('analytics_checkpoints', 'id')
    op.drop_column('analytics_checkpoints', 'last_processed_location_id')
    op.drop_constraint(op.f('device_configs_vehicle_id_key'), 'device_configs', type_='unique')
    op.drop_index(op.f('ix_device_configs_vehicle_id'), table_name='device_configs')
    op.create_index(op.f('ix_device_configs_vehicle_id'), 'device_configs', ['vehicle_id'], unique=True)
    op.drop_constraint(op.f('uq_driver_date'), 'driver_daily_summaries', type_='unique')
    op.add_column('fleet_daily_summaries', sa.Column('avg_fuel_efficiency', sa.Float(), nullable=True))
    op.add_column('fleet_daily_summaries', sa.Column('total_co2_emissions', sa.Float(), nullable=True))
    op.add_column('fleet_daily_summaries', sa.Column('avg_driver_score', sa.Float(), nullable=True))
    op.drop_constraint(op.f('fleet_daily_summaries_date_key'), 'fleet_daily_summaries', type_='unique')
    op.drop_index(op.f('ix_fleet_daily_summaries_date'), table_name='fleet_daily_summaries')
    op.create_index(op.f('ix_fleet_daily_summaries_date'), 'fleet_daily_summaries', ['date'], unique=True)
    op.drop_constraint(op.f('uq_maintenance_date'), 'maintenance_summaries', type_='unique')
    op.create_index(op.f('ix_notification_histories_source_event_id'), 'notification_histories', ['source_event_id'], unique=False)
    op.drop_constraint(op.f('route_cache_cache_key_key'), 'route_cache', type_='unique')
    op.drop_index(op.f('ix_route_cache_cache_key'), table_name='route_cache')
    op.create_index(op.f('ix_route_cache_cache_key'), 'route_cache', ['cache_key'], unique=True)
    op.add_column('vehicle_daily_summaries', sa.Column('fuel_efficiency_l100km', sa.Float(), nullable=True))
    op.add_column('vehicle_daily_summaries', sa.Column('co2_emissions_kg', sa.Float(), nullable=True))
    op.add_column('vehicle_daily_summaries', sa.Column('utilization_ratio', sa.Float(), nullable=True))
    op.add_column('vehicle_daily_summaries', sa.Column('min_voltage', sa.Float(), nullable=True))
    op.add_column('vehicle_daily_summaries', sa.Column('avg_driver_score', sa.Float(), nullable=True))
    op.add_column('vehicle_daily_summaries', sa.Column('overspeeding_seconds', sa.Float(), nullable=True))
    op.add_column('vehicle_daily_summaries', sa.Column('harsh_brake_count', sa.Integer(), nullable=True))
    op.add_column('vehicle_daily_summaries', sa.Column('harsh_accel_count', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_vehicle_date'), 'vehicle_daily_summaries', type_='unique')
    op.create_unique_constraint('uq_vehicle_daily_summary', 'vehicle_daily_summaries', ['vehicle_id', 'date'])
    op.drop_constraint(op.f('vehicle_operations_vehicle_id_key'), 'vehicle_operations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('vehicle_operations_vehicle_id_key'), 'vehicle_operations', ['vehicle_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_vehicle_daily_summary', 'vehicle_daily_summaries', type_='unique')
    op.create_unique_constraint(op.f('uq_vehicle_date'), 'vehicle_daily_summaries', ['vehicle_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_column('vehicle_daily_summaries', 'harsh_accel_count')
    op.drop_column('vehicle_daily_summaries', 'harsh_brake_count')
    op.drop_column('vehicle_daily_summaries', 'overspeeding_seconds')
    op.drop_column('vehicle_daily_summaries', 'avg_driver_score')
    op.drop_column('vehicle_daily_summaries', 'min_voltage')
    op.drop_column('vehicle_daily_summaries', 'utilization_ratio')
    op.drop_column('vehicle_daily_summaries', 'co2_emissions_kg')
    op.drop_column('vehicle_daily_summaries', 'fuel_efficiency_l100km')
    op.drop_index(op.f('ix_route_cache_cache_key'), table_name='route_cache')
    op.create_index(op.f('ix_route_cache_cache_key'), 'route_cache', ['cache_key'], unique=False)
    op.create_unique_constraint(op.f('route_cache_cache_key_key'), 'route_cache', ['cache_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_notification_histories_source_event_id'), table_name='notification_histories')
    op.create_unique_constraint(op.f('uq_maintenance_date'), 'maintenance_summaries', ['vehicle_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_fleet_daily_summaries_date'), table_name='fleet_daily_summaries')
    op.create_index(op.f('ix_fleet_daily_summaries_date'), 'fleet_daily_summaries', ['date'], unique=False)
    op.create_unique_constraint(op.f('fleet_daily_summaries_date_key'), 'fleet_daily_summaries', ['date'], postgresql_nulls_not_distinct=False)
    op.drop_column('fleet_daily_summaries', 'avg_driver_score')
    op.drop_column('fleet_daily_summaries', 'total_co2_emissions')
    op.drop_column('fleet_daily_summaries', 'avg_fuel_efficiency')
    op.create_unique_constraint(op.f('uq_driver_date'), 'driver_daily_summaries', ['driver_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_device_configs_vehicle_id'), table_name='device_configs')
    op.create_index(op.f('ix_device_configs_vehicle_id'), 'device_configs', ['vehicle_id'], unique=False)
    op.create_unique_constraint(op.f('device_configs_vehicle_id_key'), 'device_configs', ['vehicle_id'], postgresql_nulls_not_distinct=False)
    op.add_column('analytics_checkpoints', sa.Column('last_processed_location_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('analytics_checkpoints', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('analytics_checkpoints', sa.Column('pipeline_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('analytics_checkpoints', sa.Column('last_run_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analytics_checkpoints_processor_group'), table_name='analytics_checkpoints')
    op.create_index(op.f('ix_analytics_checkpoints_id'), 'analytics_checkpoints', ['id'], unique=False)
    op.create_unique_constraint(op.f('analytics_checkpoints_pipeline_name_key'), 'analytics_checkpoints', ['pipeline_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('analytics_checkpoints', 'updated_at')
    op.drop_column('analytics_checkpoints', 'last_processed_id')
    op.drop_column('analytics_checkpoints', 'processor_group')
    # ### end Alembic commands ###
